#!/usr/bin/env bash
set -euo pipefail

BIN_DIR="${PWD}/bin/labs/"

HOST="https://houston.kubernetes-vm.${INSTRUQT_PARTICIPANT_ID}.instruqt.io/v1"
NAMESPACE="astronomer"

USER="admin@astronomer.io"
PASS="admin"

# create k8s secret
kubectl -n "${NAMESPACE}" \
  create secret generic ap-e2e-test-creds \
  --from-literal=ASTRO_USER="$USER" \
  --from-literal=ASTRO_PASS="$PASS"

# Fill in file for houston post
sed -i \
  -e "s/__USER__/$USER/" \
  -e "s/__PASS__/$PASS/" \
  "$BIN_DIR/create-initial-user.json"

# Create new user by posting to houston
NEW_USER=$(curl --insecure -v "$HOST" \
  -H "content-type: application/json" \
  -d "@$BIN_DIR/create-initial-user.json")

echo $NEW_USER

TOKEN=$(echo "$NEW_USER" | jq -r '.data.createUser.token.value')

echo "export TOKEN=$TOKEN" >> /root/.bashrc

# restore the JSON file
git checkout "$BIN_DIR/create-initial-user.json"

exit 0